import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Shield, Smartphone, Key } from "lucide-react";
import { useProfile } from "@/hooks/use-profile";
import { useToast } from "@/hooks/use-toast";

interface TwoFactorSetupDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  isEnabled: boolean;
}

export default function TwoFactorSetupDialog({ 
  open, 
  onOpenChange, 
  isEnabled 
}: TwoFactorSetupDialogProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [verificationCode, setVerificationCode] = useState("");
  const [step, setStep] = useState<'setup' | 'verify'>('setup');
  
  const { toggleTwoFactor } = useProfile();
  const { toast } = useToast();

  const handleEnable = async () => {
    setIsLoading(true);
    try {
      const success = await toggleTwoFactor(true);
      if (success) {
        setStep('verify');
        toast({
          title: "2FA Setup Started",
          description: "Please check your authenticator app for the verification code.",
        });
      }
    } catch (error) {
      console.error('Error enabling 2FA:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleVerify = async () => {
    if (!verificationCode || verificationCode.length !== 6) {
      toast({
        title: "Invalid Code",
        description: "Please enter a valid 6-digit verification code.",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    try {
      // In a real implementation, you would verify the code with your backend
      // For now, we'll simulate a successful verification
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      toast({
        title: "2FA Enabled",
        description: "Two-factor authentication has been successfully enabled.",
      });
      onOpenChange(false);
      setStep('setup');
      setVerificationCode("");
    } catch (error) {
      console.error('Error verifying 2FA code:', error);
      toast({
        title: "Verification Failed",
        description: "Invalid verification code. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleDisable = async () => {
    setIsLoading(true);
    try {
      const success = await toggleTwoFactor(false);
      if (success) {
        toast({
          title: "2FA Disabled",
          description: "Two-factor authentication has been disabled.",
        });
        onOpenChange(false);
      }
    } catch (error) {
      console.error('Error disabling 2FA:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = () => {
    setStep('setup');
    setVerificationCode("");
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5" />
            Two-Factor Authentication
          </DialogTitle>
          <DialogDescription>
            {isEnabled 
              ? "Two-factor authentication is currently enabled for your account."
              : "Add an extra layer of security to your account with two-factor authentication."
            }
          </DialogDescription>
        </DialogHeader>

        {isEnabled ? (
          <div className="space-y-4">
            <div className="bg-green-50 dark:bg-green-950/20 border border-green-200 dark:border-green-800 rounded-lg p-4">
              <div className="flex items-center gap-2 text-green-800 dark:text-green-200">
                <Shield className="h-4 w-4" />
                <span className="text-sm font-medium">2FA is Active</span>
              </div>
              <p className="text-sm text-green-700 dark:text-green-300 mt-1">
                Your account is protected with two-factor authentication.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="text-sm font-medium">What happens when 2FA is enabled:</h4>
              <ul className="text-sm text-muted-foreground space-y-1">
                <li>• You'll need to enter a verification code when signing in</li>
                <li>• Codes are generated by your authenticator app</li>
                <li>• Backup codes are provided for emergency access</li>
              </ul>
            </div>
          </div>
        ) : step === 'setup' ? (
          <div className="space-y-6">
            <div className="space-y-4">
              <h4 className="text-sm font-medium">How to set up 2FA:</h4>
              <div className="space-y-3">
                <div className="flex items-start gap-3">
                  <div className="flex-shrink-0 w-6 h-6 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-xs font-medium">
                    1
                  </div>
                  <div>
                    <p className="text-sm font-medium">Install an authenticator app</p>
                    <p className="text-xs text-muted-foreground">
                      Use apps like Google Authenticator, Authy, or Microsoft Authenticator
                    </p>
                  </div>
                </div>
                
                <div className="flex items-start gap-3">
                  <div className="flex-shrink-0 w-6 h-6 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-xs font-medium">
                    2
                  </div>
                  <div>
                    <p className="text-sm font-medium">Scan the QR code</p>
                    <p className="text-xs text-muted-foreground">
                      The app will generate a QR code for you to scan
                    </p>
                  </div>
                </div>
                
                <div className="flex items-start gap-3">
                  <div className="flex-shrink-0 w-6 h-6 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-xs font-medium">
                    3
                  </div>
                  <div>
                    <p className="text-sm font-medium">Enter verification code</p>
                    <p className="text-xs text-muted-foreground">
                      Enter the 6-digit code from your authenticator app
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-muted/50 p-4 rounded-lg">
              <div className="flex items-center gap-2 mb-2">
                <Smartphone className="h-4 w-4" />
                <span className="text-sm font-medium">Demo QR Code</span>
              </div>
              <div className="bg-white p-4 rounded border-2 border-dashed border-muted-foreground/25 flex items-center justify-center">
                <div className="text-center">
                  <div className="w-32 h-32 bg-muted rounded flex items-center justify-center mb-2">
                    <Key className="h-8 w-8 text-muted-foreground" />
                  </div>
                  <p className="text-xs text-muted-foreground">
                    QR Code would appear here
                  </p>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="text-center">
              <h4 className="text-sm font-medium mb-2">Enter Verification Code</h4>
              <p className="text-xs text-muted-foreground mb-4">
                Enter the 6-digit code from your authenticator app
              </p>
            </div>
            
            <div className="flex justify-center">
              <Input
                type="text"
                placeholder="000000"
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                className="text-center text-lg tracking-widest w-32"
                maxLength={6}
              />
            </div>
          </div>
        )}

        <DialogFooter>
          <Button type="button" variant="outline" onClick={handleClose}>
            Cancel
          </Button>
          {isEnabled ? (
            <Button 
              variant="destructive" 
              onClick={handleDisable} 
              disabled={isLoading}
            >
              {isLoading ? "Disabling..." : "Disable 2FA"}
            </Button>
          ) : step === 'setup' ? (
            <Button onClick={handleEnable} disabled={isLoading}>
              {isLoading ? "Setting up..." : "Enable 2FA"}
            </Button>
          ) : (
            <Button onClick={handleVerify} disabled={isLoading || verificationCode.length !== 6}>
              {isLoading ? "Verifying..." : "Verify & Enable"}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
