// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[...slug]" | "/auth"
type AppRouteHandlerRoutes = "/api" | "/api/logo" | "/logo"
type PageRoutes = "/Alerts" | "/ApiKeyManagement" | "/Auth" | "/Chat" | "/Clients" | "/CombinedAnalytics" | "/Contracts" | "/CostAnalytics" | "/Dashboard" | "/Dispatch" | "/Drivers" | "/FleetAuth" | "/Forbidden" | "/FuelLogs" | "/InvitationLetter" | "/Invoices" | "/Maintenance" | "/NotFound" | "/Profile" | "/Quotations" | "/Reports" | "/SecurityEscorts" | "/Settings" | "/SpareParts" | "/TripAnalytics" | "/TripFinance" | "/Trips" | "/VehicleIncidentReports" | "/VehicleInspections" | "/VehicleLeasing" | "/Vehicles"
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[...slug]": { "slug": string[]; }
  "/Alerts": {}
  "/api": {}
  "/api/logo": {}
  "/ApiKeyManagement": {}
  "/auth": {}
  "/Auth": {}
  "/Chat": {}
  "/Clients": {}
  "/CombinedAnalytics": {}
  "/Contracts": {}
  "/CostAnalytics": {}
  "/Dashboard": {}
  "/Dispatch": {}
  "/Drivers": {}
  "/FleetAuth": {}
  "/Forbidden": {}
  "/FuelLogs": {}
  "/InvitationLetter": {}
  "/Invoices": {}
  "/logo": {}
  "/Maintenance": {}
  "/NotFound": {}
  "/Profile": {}
  "/Quotations": {}
  "/Reports": {}
  "/SecurityEscorts": {}
  "/Settings": {}
  "/SpareParts": {}
  "/TripAnalytics": {}
  "/TripFinance": {}
  "/Trips": {}
  "/VehicleIncidentReports": {}
  "/VehicleInspections": {}
  "/VehicleLeasing": {}
  "/Vehicles": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
