// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Import centralized API keys configuration
import { SUPABASE_URL, SUPABASE_ANON_KEY, validateAPIKeys } from "@/config/api-keys";

// NOTE: Do not validate before client creation to avoid circular init

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Derive Functions URL to avoid proxy/CORS quirks, allow explicit override
const FUNCTIONS_URL = (() => {
  const explicit = process.env.NEXT_PUBLIC_SUPABASE_FUNCTIONS_URL as
    | string
    | undefined;
  if (explicit) return explicit;
  try {
    const u = new URL(SUPABASE_URL);
    // Use the same domain as the main Supabase URL for Edge Functions
    return `${u.protocol}//${u.host}`;
  } catch {
    return undefined;
  }
})();

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    // Temporarily disable custom functions URL to fix CORS issues
    // ...(FUNCTIONS_URL ? { functions: { url: FUNCTIONS_URL } } : {}),
    // Add auth configuration to handle cross-domain issues
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: "pkce",
      // Note: onAuthStateChange is not supported in this version
    },
    // Global headers for better compatibility
    global: {
      headers: {
        "X-Client-Info": "supabase-js/2.x",
      },
    },
    // Add retry configuration for better network handling
    db: {
      schema: "public",
    },
    // Add realtime configuration
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Run API key validation after client is ready (non-blocking, browser only)
if (typeof window !== "undefined") {
  void (async () => {
    try {
      await validateAPIKeys();
    } catch {
      // swallow validation errors to avoid breaking runtime
    }
  })();
}

// Add global error handler for network and auth issues
if (typeof window !== "undefined") {
  // Handle network errors globally
  window.addEventListener("unhandledrejection", (event) => {
    if (event.reason?.message?.includes("Failed to fetch")) {
      console.warn(
        "Network error detected, this might be a temporary connection issue"
      );
      event.preventDefault();
    }
  });

  // Handle authentication errors globally
  window.addEventListener("unhandledrejection", (event) => {
    const error = event.reason;
    if (
      error?.message?.includes("Invalid Refresh Token") ||
      error?.message?.includes("Refresh Token Not Found") ||
      error?.message?.includes("refresh_token_not_found")
    ) {
      console.warn(
        "Refresh token error detected, clearing session and redirecting to auth"
      );

      // Clear all auth-related storage
      try {
        localStorage.removeItem(
          "sb-" + SUPABASE_URL.split("//")[1].split(".")[0] + "-auth-token"
        );
        sessionStorage.removeItem("supabase.auth.token");
        sessionStorage.removeItem(
          "sb-" + SUPABASE_URL.split("//")[1].split(".")[0] + "-auth-token"
        );
      } catch (e) {
        console.warn("Failed to clear auth storage:", e);
      }

      // Redirect to auth page
      if (window.location.pathname !== "/auth") {
        window.location.href = "/auth";
      }

      event.preventDefault();
    }
  });
}
