// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Import centralized API keys configuration
import {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  validateAPIKeys,
} from "@/config/api-keys";

// Validate API keys on startup
validateAPIKeys();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Derive Functions URL to avoid proxy/CORS quirks, allow explicit override
const FUNCTIONS_URL = (() => {
  const explicit = process.env.NEXT_PUBLIC_SUPABASE_FUNCTIONS_URL as
    | string
    | undefined;
  if (explicit) return explicit;
  try {
    const u = new URL(SUPABASE_URL);
    // Replace <ref>.supabase.co with <ref>.functions.supabase.co (or .in)
    const host = u.host
      .replace(".supabase.co", ".functions.supabase.co")
      .replace(".supabase.in", ".functions.supabase.in");
    return `${u.protocol}//${host}`;
  } catch {
    return undefined;
  }
})();

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    // Direct edge function calls to the dedicated Functions domain
    ...(FUNCTIONS_URL ? { functions: { url: FUNCTIONS_URL } } : {}),
    // Add auth configuration to handle cross-domain issues
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: "pkce",
      // Note: onAuthStateChange is not supported in this version
    },
    // Global headers for better compatibility
    global: {
      headers: {
        "X-Client-Info": "supabase-js/2.x",
      },
    },
  }
);
