// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Read from Vite environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as
  | string
  | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY. Please set them in your .env file."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Derive Functions URL to avoid proxy/CORS quirks, allow explicit override
const FUNCTIONS_URL = (() => {
  const explicit = (import.meta as any).env?.VITE_SUPABASE_FUNCTIONS_URL as
    | string
    | undefined;
  if (explicit) return explicit;
  try {
    const u = new URL(SUPABASE_URL);
    // Replace <ref>.supabase.co with <ref>.functions.supabase.co (or .in)
    const host = u.host
      .replace(".supabase.co", ".functions.supabase.co")
      .replace(".supabase.in", ".functions.supabase.in");
    return `${u.protocol}//${host}`;
  } catch {
    return undefined;
  }
})();

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    // Direct edge function calls to the dedicated Functions domain
    ...(FUNCTIONS_URL ? { functions: { url: FUNCTIONS_URL } } : {}),
    // Add auth configuration to handle cross-domain issues
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: "pkce",
      // Ensure proper logout handling
      onAuthStateChange: (event, session) => {
        console.log("Auth state change:", event, session?.user?.email);
      },
    },
    // Global headers for better compatibility
    global: {
      headers: {
        "X-Client-Info": "supabase-js/2.x",
      },
    },
  }
);
